In [2]:
import numpy as np
import pandas as pd

In [3]:
def print_basics(array):
    """
    func to print the basic attributes of a given array
    """
    
    print("array ","\n", array)
    print("array.shape ","\n", array.shape)
    print("array.size ","\n", array.size)
    print("array.ndim ","\n", array.ndim)

### experimenting with array shapes, axis,stack, concatenate

Working with 1d arrays 

In [4]:

a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(7,10)
d = np.arange(10,13)
e = np.arange(13,16)
f = np.arange(16,19)


print(a, b, c, d, e)

[1 2 3] [4 5 6] [7 8 9] [10 11 12] [13 14 15]


In [5]:
array = np.concatenate([a,b,c,d], axis = 0)
print_basics(array)

array  
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
array.shape  
 (12,)
array.size  
 12
array.ndim  
 1


In [7]:
array = np.hstack([a,b,c,d])
print_basics(array)

array  
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
array.shape  
 (12,)
array.size  
 12
array.ndim  
 1


In [8]:
array_a = np.vstack([a,b,c,d])
print_basics(array_a)

array  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array.shape  
 (4, 3)
array.size  
 12
array.ndim  
 2


In [11]:
array_b = np.vstack((e,f))
print_basics(array_b)

array  
 [[13 14 15]
 [16 17 18]]
array.shape  
 (2, 3)
array.size  
 6
array.ndim  
 2


In [12]:
array_c = np.concatenate([array_a,array_b], axis = 0)
print_basics(array_c)

array  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
array.shape  
 (6, 3)
array.size  
 18
array.ndim  
 2


In [13]:
array_c = np.vstack([array_a, array_b])
print_basics(array_c)

array  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
array.shape  
 (6, 3)
array.size  
 18
array.ndim  
 2


Working with 2d arrays 




In [14]:
aa = np.arange(0,6,1)
aa = aa.reshape((3,2))


In [15]:
bb = aa+6
cc = aa+6*2
dd = aa+6*3

In [16]:
print_basics(aa)

array  
 [[0 1]
 [2 3]
 [4 5]]
array.shape  
 (3, 2)
array.size  
 6
array.ndim  
 2


In [17]:
aaa = np.stack([aa,bb,cc,dd], axis = 0)
print_basics(aaa)

array  
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
array.shape  
 (4, 3, 2)
array.size  
 24
array.ndim  
 3


### experimenting stack across different axis

In [18]:
a_0 = np.arange(0,6,1)

In [19]:
a_0 = a_0.reshape((3,2))
print_basics(a_0)

array  
 [[0 1]
 [2 3]
 [4 5]]
array.shape  
 (3, 2)
array.size  
 6
array.ndim  
 2


In [20]:
a_1 = a_0+6*1
a_2 = a_0+6*2
a_3 = a_0+6*3

In [21]:
print_basics(a_2)

array  
 [[12 13]
 [14 15]
 [16 17]]
array.shape  
 (3, 2)
array.size  
 6
array.ndim  
 2


In [22]:
stack_0 = np.stack([a_0,a_1,a_2,a_3], axis=0)
print_basics(stack_0)

array  
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
array.shape  
 (4, 3, 2)
array.size  
 24
array.ndim  
 3


In [23]:
stack_0[3]

array([[18, 19],
       [20, 21],
       [22, 23]])

In [28]:
print(a_0)
print(a_1)
print(a_2)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[12 13]
 [14 15]
 [16 17]]


In [24]:
stack_1 = np.stack([a_0, a_1, a_2, a_3], axis = 1)
print_basics(stack_1)

array  
 [[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]
array.shape  
 (3, 4, 2)
array.size  
 24
array.ndim  
 3


In [26]:
stack_2 = np.stack([a_0,a_1,a_2,a_3], axis =2)
print_basics(stack_2)

array  
 [[[ 0  6 12 18]
  [ 1  7 13 19]]

 [[ 2  8 14 20]
  [ 3  9 15 21]]

 [[ 4 10 16 22]
  [ 5 11 17 23]]]
array.shape  
 (3, 2, 4)
array.size  
 24
array.ndim  
 3


### Experimenting with multi-indexing

In [ ]:
x = np.arange(10)
y = x**2

In [ ]:
data = {"X":x,
       "Y":y,
        "Categoty":["Bloop" if i<5 else "Poop" for i in x],
        "state":["solid","solid","solid","liquid","liquid","liquid","gas","gas","gas","gas"]}


In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.set_index(["state","Categoty"], inplace = True)

In [ ]:
df.set_index(["Categoty", "state"], inplace = True)

In [ ]:
df

In [ ]:
df.index.levels

In [ ]:
df.index.labels

In [ ]:
df.index.names

In [ ]:
df.index.values