In [1]:
import numpy as np

In [2]:
def print_basics(array):
    """
    func to print the basic attributes of a given array
    """
    
    print("array ","\n", array)
    print("array.shape ","\n", array.shape)
    print("array.size ","\n", array.size)
    print("array.ndim ","\n", array.ndim)

# Appendix

### experimenting with array shapes, axis, hstack, vstack, concat

Working with 1d arrays 

In [3]:

a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(7,10)
d = np.arange(10,13)
e = np.arange(13,16)
f = np.arange(16,19)


print(a, b, c, d, e)

[1 2 3] [4 5 6] [7 8 9] [10 11 12] [13 14 15]


In [10]:
array = np.concatenate([a,b,c,d], axis = 0)
print_basics(array)

array  
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
array.shape  
 (12,)
array.size  
 12
array.ndim  
 1


In [11]:
array = np.hstack([a,b,c,d],)
print_basics(array)

array  
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
array.shape  
 (12,)
array.size  
 12
array.ndim  
 1


In [12]:
array_a = np.vstack([a,b,c,d])
print_basics(array_a)

array  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array.shape  
 (4, 3)
array.size  
 12
array.ndim  
 2


In [13]:
array_b = np.vstack([e,f,])
print_basics(array_b)

array  
 [[13 14 15]
 [16 17 18]]
array.shape  
 (2, 3)
array.size  
 6
array.ndim  
 2


In [22]:
array_c = np.concatenate([array_a,array_b], axis = 0)
print_basics(array_c)

array  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
array.shape  
 (6, 3)
array.size  
 18
array.ndim  
 2


In [20]:
array_c = np.vstack([array_a, array_b])
print_basics(array_c)

array  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
array.shape  
 (6, 3)
array.size  
 18
array.ndim  
 2


Working with 2d arrays 




In [76]:
aa = np.arange(0,6,1)
aa = aa.reshape((3,2))


In [77]:
bb = aa+6
cc = aa+6*2
dd = aa+6*3

In [102]:
print_basics(aa)

array  
 [[0 1]
 [2 3]
 [4 5]]
array.shape  
 (3, 2)
array.size  
 6
array.ndim  
 2


In [109]:
aaa = np.stack([aa,bb,cc,dd], axis = 0)
print_basics(aaa)

array  
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
array.shape  
 (4, 3, 2)
array.size  
 24
array.ndim  
 3
